// Code generated by go-swagger; DO NOT EDIT.

package default_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ControllersDefaultControllerMonoframePixelmapPutOKCode is the HTTP code returned for type ControllersDefaultControllerMonoframePixelmapPutOK
const ControllersDefaultControllerMonoframePixelmapPutOKCode int = 200

/*ControllersDefaultControllerMonoframePixelmapPutOK Success

swagger:response controllersDefaultControllerMonoframePixelmapPutOK
*/
type ControllersDefaultControllerMonoframePixelmapPutOK struct {
}

// NewControllersDefaultControllerMonoframePixelmapPutOK creates ControllersDefaultControllerMonoframePixelmapPutOK with default headers values
func NewControllersDefaultControllerMonoframePixelmapPutOK() *ControllersDefaultControllerMonoframePixelmapPutOK {

	return &ControllersDefaultControllerMonoframePixelmapPutOK{}
}

// WriteResponse to the client
func (o *ControllersDefaultControllerMonoframePixelmapPutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
