// Code generated by go-swagger; DO NOT EDIT.

package default_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ControllersDefaultControllerMonolinePutHandlerFunc turns a function with the right signature into a controllers default controller monoline put handler
type ControllersDefaultControllerMonolinePutHandlerFunc func(ControllersDefaultControllerMonolinePutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ControllersDefaultControllerMonolinePutHandlerFunc) Handle(params ControllersDefaultControllerMonolinePutParams) middleware.Responder {
	return fn(params)
}

// ControllersDefaultControllerMonolinePutHandler interface for that can handle valid controllers default controller monoline put params
type ControllersDefaultControllerMonolinePutHandler interface {
	Handle(ControllersDefaultControllerMonolinePutParams) middleware.Responder
}

// NewControllersDefaultControllerMonolinePut creates a new http.Handler for the controllers default controller monoline put operation
func NewControllersDefaultControllerMonolinePut(ctx *middleware.Context, handler ControllersDefaultControllerMonolinePutHandler) *ControllersDefaultControllerMonolinePut {
	return &ControllersDefaultControllerMonolinePut{Context: ctx, Handler: handler}
}

/*ControllersDefaultControllerMonolinePut swagger:route PUT /monoline default_controller controllersDefaultControllerMonolinePut

Sets single line

*/
type ControllersDefaultControllerMonolinePut struct {
	Context *middleware.Context
	Handler ControllersDefaultControllerMonolinePutHandler
}

func (o *ControllersDefaultControllerMonolinePut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewControllersDefaultControllerMonolinePutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
