// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"mustrum/restapi/operations/default_controller"
)

// NewMustrumAPI creates a new Mustrum instance
func NewMustrumAPI(spec *loads.Document) *MustrumAPI {
	return &MustrumAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		DefaultControllerControllersDefaultControllerAllPixelsGetHandler: default_controller.ControllersDefaultControllerAllPixelsGetHandlerFunc(func(params default_controller.ControllersDefaultControllerAllPixelsGetParams) middleware.Responder {
			return middleware.NotImplemented("operation DefaultControllerControllersDefaultControllerAllPixelsGet has not yet been implemented")
		}),
		DefaultControllerControllersDefaultControllerDotXPutHandler: default_controller.ControllersDefaultControllerDotXPutHandlerFunc(func(params default_controller.ControllersDefaultControllerDotXPutParams) middleware.Responder {
			return middleware.NotImplemented("operation DefaultControllerControllersDefaultControllerDotXPut has not yet been implemented")
		}),
		DefaultControllerControllersDefaultControllerMonoframePixelmapPutHandler: default_controller.ControllersDefaultControllerMonoframePixelmapPutHandlerFunc(func(params default_controller.ControllersDefaultControllerMonoframePixelmapPutParams) middleware.Responder {
			return middleware.NotImplemented("operation DefaultControllerControllersDefaultControllerMonoframePixelmapPut has not yet been implemented")
		}),
		DefaultControllerControllersDefaultControllerMonolinePutHandler: default_controller.ControllersDefaultControllerMonolinePutHandlerFunc(func(params default_controller.ControllersDefaultControllerMonolinePutParams) middleware.Responder {
			return middleware.NotImplemented("operation DefaultControllerControllersDefaultControllerMonolinePut has not yet been implemented")
		}),
		DefaultControllerControllersDefaultControllerShowGetHandler: default_controller.ControllersDefaultControllerShowGetHandlerFunc(func(params default_controller.ControllersDefaultControllerShowGetParams) middleware.Responder {
			return middleware.NotImplemented("operation DefaultControllerControllersDefaultControllerShowGet has not yet been implemented")
		}),
	}
}

/*MustrumAPI A third cut at writing the code initial formed in web.py for the PiMoroni UnicornHAT
 */
type MustrumAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// DefaultControllerControllersDefaultControllerAllPixelsGetHandler sets the operation handler for the controllers default controller all pixels get operation
	DefaultControllerControllersDefaultControllerAllPixelsGetHandler default_controller.ControllersDefaultControllerAllPixelsGetHandler
	// DefaultControllerControllersDefaultControllerDotXPutHandler sets the operation handler for the controllers default controller dot x put operation
	DefaultControllerControllersDefaultControllerDotXPutHandler default_controller.ControllersDefaultControllerDotXPutHandler
	// DefaultControllerControllersDefaultControllerMonoframePixelmapPutHandler sets the operation handler for the controllers default controller monoframe pixelmap put operation
	DefaultControllerControllersDefaultControllerMonoframePixelmapPutHandler default_controller.ControllersDefaultControllerMonoframePixelmapPutHandler
	// DefaultControllerControllersDefaultControllerMonolinePutHandler sets the operation handler for the controllers default controller monoline put operation
	DefaultControllerControllersDefaultControllerMonolinePutHandler default_controller.ControllersDefaultControllerMonolinePutHandler
	// DefaultControllerControllersDefaultControllerShowGetHandler sets the operation handler for the controllers default controller show get operation
	DefaultControllerControllersDefaultControllerShowGetHandler default_controller.ControllersDefaultControllerShowGetHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *MustrumAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MustrumAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MustrumAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MustrumAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MustrumAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MustrumAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MustrumAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MustrumAPI
func (o *MustrumAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.DefaultControllerControllersDefaultControllerAllPixelsGetHandler == nil {
		unregistered = append(unregistered, "default_controller.ControllersDefaultControllerAllPixelsGetHandler")
	}

	if o.DefaultControllerControllersDefaultControllerDotXPutHandler == nil {
		unregistered = append(unregistered, "default_controller.ControllersDefaultControllerDotXPutHandler")
	}

	if o.DefaultControllerControllersDefaultControllerMonoframePixelmapPutHandler == nil {
		unregistered = append(unregistered, "default_controller.ControllersDefaultControllerMonoframePixelmapPutHandler")
	}

	if o.DefaultControllerControllersDefaultControllerMonolinePutHandler == nil {
		unregistered = append(unregistered, "default_controller.ControllersDefaultControllerMonolinePutHandler")
	}

	if o.DefaultControllerControllersDefaultControllerShowGetHandler == nil {
		unregistered = append(unregistered, "default_controller.ControllersDefaultControllerShowGetHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MustrumAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MustrumAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *MustrumAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *MustrumAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *MustrumAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MustrumAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the mustrum API
func (o *MustrumAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *MustrumAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/all_pixels"] = default_controller.NewControllersDefaultControllerAllPixelsGet(o.context, o.DefaultControllerControllersDefaultControllerAllPixelsGetHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/dot/{x}"] = default_controller.NewControllersDefaultControllerDotXPut(o.context, o.DefaultControllerControllersDefaultControllerDotXPutHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/monoframe/{pixelmap}"] = default_controller.NewControllersDefaultControllerMonoframePixelmapPut(o.context, o.DefaultControllerControllersDefaultControllerMonoframePixelmapPutHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/monoline"] = default_controller.NewControllersDefaultControllerMonolinePut(o.context, o.DefaultControllerControllersDefaultControllerMonolinePutHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/show"] = default_controller.NewControllersDefaultControllerShowGet(o.context, o.DefaultControllerControllersDefaultControllerShowGetHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MustrumAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *MustrumAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *MustrumAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *MustrumAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
