// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Mustrum
A third cut at writing the code initial formed in web.py for the PiMoroni UnicornHAT



    Schemes:
      http
    Host: 192.168.1.88:8080
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
