// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Pixelmap pixelmap
// swagger:model pixelmap
type Pixelmap [][]*Colour

// Validate validates this pixelmap
func (m Pixelmap) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		for ii := 0; ii < len(m[i]); ii++ {
			if swag.IsZero(m[i][ii]) { // not required
				continue
			}

			if m[i][ii] != nil {
				if err := m[i][ii].Validate(formats); err != nil {
					if ve, ok := err.(*errors.Validation); ok {
						return ve.ValidateName(strconv.Itoa(i) + "." + strconv.Itoa(ii))
					}
					return err
				}
			}

		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
