// Code generated by go-swagger; DO NOT EDIT.

package default_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ControllersDefaultControllerMonoframePixelmapPutHandlerFunc turns a function with the right signature into a controllers default controller monoframe pixelmap put handler
type ControllersDefaultControllerMonoframePixelmapPutHandlerFunc func(ControllersDefaultControllerMonoframePixelmapPutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ControllersDefaultControllerMonoframePixelmapPutHandlerFunc) Handle(params ControllersDefaultControllerMonoframePixelmapPutParams) middleware.Responder {
	return fn(params)
}

// ControllersDefaultControllerMonoframePixelmapPutHandler interface for that can handle valid controllers default controller monoframe pixelmap put params
type ControllersDefaultControllerMonoframePixelmapPutHandler interface {
	Handle(ControllersDefaultControllerMonoframePixelmapPutParams) middleware.Responder
}

// NewControllersDefaultControllerMonoframePixelmapPut creates a new http.Handler for the controllers default controller monoframe pixelmap put operation
func NewControllersDefaultControllerMonoframePixelmapPut(ctx *middleware.Context, handler ControllersDefaultControllerMonoframePixelmapPutHandler) *ControllersDefaultControllerMonoframePixelmapPut {
	return &ControllersDefaultControllerMonoframePixelmapPut{Context: ctx, Handler: handler}
}

/*ControllersDefaultControllerMonoframePixelmapPut swagger:route PUT /monoframe/{pixelmap} default_controller controllersDefaultControllerMonoframePixelmapPut

Shows single frame

*/
type ControllersDefaultControllerMonoframePixelmapPut struct {
	Context *middleware.Context
	Handler ControllersDefaultControllerMonoframePixelmapPutHandler
}

func (o *ControllersDefaultControllerMonoframePixelmapPut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewControllersDefaultControllerMonoframePixelmapPutParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
