// Code generated by go-swagger; DO NOT EDIT.

package default_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ControllersDefaultControllerMonolinePutOKCode is the HTTP code returned for type ControllersDefaultControllerMonolinePutOK
const ControllersDefaultControllerMonolinePutOKCode int = 200

/*ControllersDefaultControllerMonolinePutOK Success

swagger:response controllersDefaultControllerMonolinePutOK
*/
type ControllersDefaultControllerMonolinePutOK struct {
}

// NewControllersDefaultControllerMonolinePutOK creates ControllersDefaultControllerMonolinePutOK with default headers values
func NewControllersDefaultControllerMonolinePutOK() *ControllersDefaultControllerMonolinePutOK {

	return &ControllersDefaultControllerMonolinePutOK{}
}

// WriteResponse to the client
func (o *ControllersDefaultControllerMonolinePutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
