// Code generated by go-swagger; DO NOT EDIT.

package default_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "mustrum/models"
)

// NewControllersDefaultControllerMonoframePixelmapPutParams creates a new ControllersDefaultControllerMonoframePixelmapPutParams object
// no default values defined in spec.
func NewControllersDefaultControllerMonoframePixelmapPutParams() ControllersDefaultControllerMonoframePixelmapPutParams {

	return ControllersDefaultControllerMonoframePixelmapPutParams{}
}

// ControllersDefaultControllerMonoframePixelmapPutParams contains all the bound params for the controllers default controller monoframe pixelmap put operation
// typically these are obtained from a http.Request
//
// swagger:parameters controllers.default_controller.monoframe_pixelmap_put
type ControllersDefaultControllerMonoframePixelmapPutParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Colour *models.Colour
	/*map of pixel
	  Required: true
	  In: path
	*/
	Pixelmap string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewControllersDefaultControllerMonoframePixelmapPutParams() beforehand.
func (o *ControllersDefaultControllerMonoframePixelmapPutParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Colour
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("colour", "body"))
			} else {
				res = append(res, errors.NewParseError("colour", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Colour = &body
			}
		}
	} else {
		res = append(res, errors.Required("colour", "body"))
	}
	rPixelmap, rhkPixelmap, _ := route.Params.GetOK("pixelmap")
	if err := o.bindPixelmap(rPixelmap, rhkPixelmap, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindPixelmap binds and validates parameter Pixelmap from path.
func (o *ControllersDefaultControllerMonoframePixelmapPutParams) bindPixelmap(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Pixelmap = raw

	return nil
}
