// Code generated by go-swagger; DO NOT EDIT.

package default_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ControllersDefaultControllerDotXPutOKCode is the HTTP code returned for type ControllersDefaultControllerDotXPutOK
const ControllersDefaultControllerDotXPutOKCode int = 200

/*ControllersDefaultControllerDotXPutOK Success

swagger:response controllersDefaultControllerDotXPutOK
*/
type ControllersDefaultControllerDotXPutOK struct {
}

// NewControllersDefaultControllerDotXPutOK creates ControllersDefaultControllerDotXPutOK with default headers values
func NewControllersDefaultControllerDotXPutOK() *ControllersDefaultControllerDotXPutOK {

	return &ControllersDefaultControllerDotXPutOK{}
}

// WriteResponse to the client
func (o *ControllersDefaultControllerDotXPutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
